# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7b7affbfe548a69aff042319542310a953e0cc80317abfa8c699b346a69efb67df03297577e709f4b4ee4d4af3c4935b068b3d00d1f8f4be67e30cc1e02a112

test:
  secret_key_base: 4c450639caa06eb4ca47b5bc0693a83cf49ea391923dd022bfe718f8f07cbd9d49fa4864dba1b9dc822968dd82b3c2508c9ab0f510998423ae6af1fc0504901e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
